name: Run Borsa Botu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu klonla
      uses: actions/checkout@v4

    - name: Python 3.10 kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Gerekli paketleri kur
      run: |
        python -m pip install --upgrade pip
        pip install yfinance
        pip install pandas
        pip install requests

    - name: Botu çalıştır
      run: python main.py