name: Run Borsa Botu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu klonla
      uses: actions/checkout@v3

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # <-- BURASI ÖNEMLİ

    - name: Gerekli paketleri kur
      run: |
        pip install yfinance
        pip install requests

    - name: Botu çalıştır
      run: python Main.py
