name: Run Borsa Botu

on:
  schedule:
    - cron: '0 9 * * *'  # Türkiye saatiyle her gün 12:00'de çalışır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu klonla
      uses: actions/checkout@v3

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Gereken paketleri kur
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Botu çalıştır
      run: |
        python main.py
